# Stubs for emoji (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from emoji.core import emojize
from emoji.core import demojize
from emoji.core import get_emoji_regexp
from emoji.unicode_codes import EMOJI_ALIAS_UNICODE
from emoji.unicode_codes import EMOJI_UNICODE
from emoji.unicode_codes import UNICODE_EMOJI
from emoji.unicode_codes import UNICODE_EMOJI_ALIAS

__email__: str
__source__: str
__license__: str


