# Stubs for emoji.unicode_codes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

EMOJI_UNICODE: Any
EMOJI_ALIAS_UNICODE: Any
UNICODE_EMOJI: Any
UNICODE_EMOJI_ALIAS: Any
